export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOMEPAGE_ROUTE = '/'
export const CART_ROUTE = '/basket'
export const SNEAKERS_ROUTE = '/sneakers'
export const PAYMENT_ROUTE = '/sneakers'
